name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # node 编译
      - name: build
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i -g hexo-cli textlint textlint-rule-ja-space-between-half-and-full-width
      - run: npm i -f
      - run: textlint --fix .\source\_posts\*.md
      - run: hexo clean
      - run: hexo g

      # docker build，并push
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #- name: Build and push
      #  uses: docker/build-push-action@v1
      #  with:
      #    username: ${{ secrets.REGISTRY_USERNAME }}
      #    password: ${{ secrets.REGISTRY_PASSWORD }}
      #    repository: blog-bkuck/blog
      #    tags: ${{ github.sha }}
      - name: Docker push
        uses: azure/docker-login@v1
        with:
          login-server: ccr.ccs.tencentyun.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -t ccr.ccs.tencentyun.com/xxx/blog:${{ github.sha }} .
          docker push ccr.ccs.tencentyun.com/xxx/blog:${{ github.sha }}

      # 让K8s应用deployment
      - run: |
      - run: |
          sed -i 's/{TAG}/${{ github.sha }}/g' deployment.yaml
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: apply -f deployment.yaml
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: '"rollout status -n blog deployment/blog"'
